name: contributions_chart
description: "GitHub katkı grafiğini gösteren Flutter widget'ı. GitHub profillerindeki katkı grafiğine benzer bir görselleştirme sağlar."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.5
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter: